// Generated by https://quicktype.io

namespace CanvasAPIWrapper
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CourseSettingsObject
    {
        [JsonProperty("allow_final_grade_override")]
        public bool? AllowFinalGradeOverride { get; set; }

        [JsonProperty("allow_student_discussion_topics")]
        public bool? AllowStudentDiscussionTopics { get; set; }

        [JsonProperty("allow_student_forum_attachments")]
        public bool? AllowStudentForumAttachments { get; set; }

        [JsonProperty("allow_student_discussion_editing")]
        public bool? AllowStudentDiscussionEditing { get; set; }

        [JsonProperty("grading_standard_enabled")]
        public bool? GradingStandardEnabled { get; set; }

        [JsonProperty("grading_standard_id")]
        public long? GradingStandardId { get; set; }

        [JsonProperty("allow_student_organized_groups")]
        public bool? AllowStudentOrganizedGroups { get; set; }

        [JsonProperty("hide_final_grades")]
        public bool? HideFinalGrades { get; set; }

        [JsonProperty("hide_distribution_graphs")]
        public bool? HideDistributionGraphs { get; set; }

        [JsonProperty("lock_all_announcements")]
        public bool? LockAllAnnouncements { get; set; }

        [JsonProperty("restrict_student_past_view")]
        public bool? RestrictStudentPastView { get; set; }

        [JsonProperty("restrict_student_future_view")]
        public bool? RestrictStudentFutureView { get; set; }

        [JsonProperty("show_announcements_on_home_page")]
        public bool? ShowAnnouncementsOnHomePage { get; set; }

        [JsonProperty("home_page_announcement_limit")]
        public long? HomePageAnnouncementLimit { get; set; }

        [JsonProperty("image_url")]
        public string ImageUrl { get; set; }

        [JsonProperty("image_id")]
        public long? ImageId { get; set; }

        [JsonProperty("image")]
        public Uri Image { get; set; }
    }
}
