// Generated by https://quicktype.io

namespace CanvasAPIWrapper
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UserObject
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("sortable_name")]
        public string SortableName { get; set; }

        [JsonProperty("short_name")]
        public string ShortName { get; set; }

        [JsonProperty("sis_user_id")]
        public string SisUserId { get; set; }

        [JsonProperty("integration_id")]
        public object IntegrationId { get; set; }

        [JsonProperty("root_account")]
        public RootAccount RootAccount { get; set; }

        [JsonProperty("avatar_url")]
        public Uri AvatarUrl { get; set; }

        [JsonProperty("enrollments")]
        public Enrollment[] Enrollments { get; set; }

        [JsonProperty("bio")]
        public string Bio { get; set; }

        [JsonProperty("custom_links")]
        public CustomLink[] CustomLinks { get; set; }

        [JsonProperty("uuid")]
        public string Uuid { get; set; }

        [JsonProperty("analytics_url", NullValueHandling = NullValueHandling.Ignore)]
        public string AnalyticsUrl { get; set; }
    }

    public partial class CustomLink
    {
        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("icon_class")]
        public string IconClass { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class Enrollment
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("user_id")]
        public long UserId { get; set; }

        [JsonProperty("course_id")]
        public long CourseId { get; set; }

        [JsonProperty("type")]
        public Role Type { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt { get; set; }

        [JsonProperty("associated_user_id")]
        public object AssociatedUserId { get; set; }

        [JsonProperty("start_at")]
        public object StartAt { get; set; }

        [JsonProperty("end_at")]
        public object EndAt { get; set; }

        [JsonProperty("course_section_id")]
        public long CourseSectionId { get; set; }

        [JsonProperty("root_account_id")]
        public long RootAccountId { get; set; }

        [JsonProperty("limit_privileges_to_course_section")]
        public bool LimitPrivilegesToCourseSection { get; set; }

        [JsonProperty("enrollment_state")]
        public EnrollmentState EnrollmentState { get; set; }

        [JsonProperty("role")]
        public Role Role { get; set; }

        [JsonProperty("role_id")]
        public long RoleId { get; set; }

        [JsonProperty("last_activity_at")]
        public DateTimeOffset LastActivityAt { get; set; }

        [JsonProperty("last_attended_at")]
        public object LastAttendedAt { get; set; }

        [JsonProperty("total_activity_time")]
        public long TotalActivityTime { get; set; }

        [JsonProperty("sis_account_id")]
        public SisAccountId SisAccountId { get; set; }

        [JsonProperty("sis_course_id")]
        public SisCourseId SisCourseId { get; set; }

        [JsonProperty("course_integration_id")]
        public object CourseIntegrationId { get; set; }

        [JsonProperty("sis_section_id")]
        public SisSectionId SisSectionId { get; set; }

        [JsonProperty("section_integration_id")]
        public object SectionIntegrationId { get; set; }

        [JsonProperty("sis_user_id")]
        public string SisUserId { get; set; }

        [JsonProperty("html_url")]
        public Uri HtmlUrl { get; set; }

        [JsonProperty("locked")]
        public bool Locked { get; set; }

        [JsonProperty("grades", NullValueHandling = NullValueHandling.Ignore)]
        public Grades Grades { get; set; }
    }

    public partial class Grades
    {
        [JsonProperty("html_url")]
        public Uri HtmlUrl { get; set; }

        [JsonProperty("grading_period_id")]
        public object GradingPeriodId { get; set; }

        [JsonProperty("current_grade")]
        public string CurrentGrade { get; set; }

        [JsonProperty("current_score")]
        public double CurrentScore { get; set; }

        [JsonProperty("final_grade")]
        public string FinalGrade { get; set; }

        [JsonProperty("final_score")]
        public double FinalScore { get; set; }

        [JsonProperty("unposted_current_score")]
        public double UnpostedCurrentScore { get; set; }

        [JsonProperty("unposted_current_grade")]
        public string UnpostedCurrentGrade { get; set; }

        [JsonProperty("unposted_final_score")]
        public double UnpostedFinalScore { get; set; }

        [JsonProperty("unposted_final_grade")]
        public string UnpostedFinalGrade { get; set; }
    }

    public enum EnrollmentState { Active };

    public enum Role { StudentEnrollment, TeacherEnrollment };

    public enum SisAccountId { OnlineScaled };

    public enum SisCourseId { COnline2019SpringPsych11114 };

    public enum SisSectionId { Online2019SpringPsych11114 };

    public enum RootAccount { ByuiInstructureCom };
}
