// Generated by https://quicktype.io

namespace CanvasAPIWrapper
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BlueprintSubscriptionsObject
    {
        [JsonProperty("id")]
        public long? Id { get; set; }

        [JsonProperty("template_id")]
        public long? TemplateId { get; set; }

        [JsonProperty("blueprint_course")]
        public BlueprintCourseObject BlueprintCourse { get; set; }
    }

    public partial class BlueprintCourseObject
    {
        [JsonProperty("id")]
        public long? Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("course_code")]
        public string CourseCode { get; set; }

        [JsonProperty("sis_course_id")]
        public string SisCourseId { get; set; }

        [JsonProperty("term_name")]
        public string TermName { get; set; }
    }
}
